### ISSUE TITLE
requirements.txt.j2 not found

### ISSUE THREAD

**Issue by kontrafiktion** [orsinium/poetry-setup#1]
Error message:

FileNotFoundError: **(venv)**/lib/python3.7/site-packages/poetry_setup/templates/requirements.txt.j2

when looking into my virtual environment, I find requirements.txt.j2 at  

**(venv)**/poetry_setup/templates/requirements.txt.j2

**Comment by kontrafiktion** [comment]
Either this should be changed:

_poetry_setup/core.py_:
`TEMPLATES_PATH = Path(path.abspath(path.dirname(__file__))) / 'templates'`

or

_setup.py_:
`data_files= ... `

 or perhaps use MANIFEST.IN (http://python-packaging.readthedocs.io/en/latest/non-code-files.html)

**Comment by orsinium** [comment]
Thank you for feedback :)

I'm use `data_files`, but [incorrect](https://stackoverflow.com/questions/11235820/setup-py-not-installing-data-files). This is very weird >.<

Now poetry-setup uses `include_package_data` instead of `data_files`. Please, upgrade poetry-setup to latest version:

```bash
pip install -U --no-cache-dir poetry-setup
```
