### ISSUE TITLE
Dev dependencies end up in install requires and requirements.txt

### ISSUE THREAD

**Issue by liamdawson** [orsinium/poetry-setup#2]
For example, [this `pyproject.toml` file](https://github.com/liamdawson/tdsc/blob/e8188b3f51b854846bf679a89dd6dd662058ac61/pyproject.toml) generate this [setup.py](https://github.com/liamdawson/tdsc/blob/e8188b3f51b854846bf679a89dd6dd662058ac61/setup.py) and this [requirements.txt](https://github.com/liamdawson/tdsc/blob/e8188b3f51b854846bf679a89dd6dd662058ac61/requirements.txt) file. (Note the presence of `black` and `sphinx` in the generated files)

**Comment by orsinium** [comment]
Oh, you're right. Thank you for report. I've fixed it. Please, update your poetry-setup to the new version (0.3.3):

```bash
pip install -U --no-cache-dir poetry-setup
```
Sorry for late answer, I didn't have ability to fix it earlier. And thank you for this library usage. I hope, you enjoy :)
