### ISSUE TITLE
Custom templates

### ISSUE THREAD

**Issue by ts-mk** [orsinium/poetry-setup#4]
While the included templates are alright, some (private) projects have different/unique requirements on the structure of those files. It would be great if it would be possible to supply a custom template path and thus use custom templates.

**Comment by orsinium** [comment]
Thank you for your proposal! Now I'm developing [dephell](https://github.com/orsinium/dephell) that will be able to read any dependencies format (poetry, Pipfile, requirements.txt) and write it into any of them. I'll notify you and close this issue when dephell will be ready to use.

**Comment by orsinium** [comment]
[DepHell](https://github.com/dephell/dephell) is ready, use [dephell deps convert](https://dephell.readthedocs.io/en/latest/cmd-deps-convert.html) to generate requirements.txt with dependencies filtering by section or extras:

```bash
dephell deps convert --from=pyproject.toml --to=requirements.txt --envs main
```
