### ISSUE TITLE
Add options to generate separate files

### ISSUE THREAD

**Issue by rominf** [orsinium/poetry-setup#6]
I want to generate `requirements.txt` because I'm satisfied with the `setup.py` that `poetry` generates itself.

**Comment by orsinium** [comment]
Thank you for your proposal :) 

They a little bit different. Requirements.txt includes dev environments.

Now I develop dephell that will replace poetry-setup, btw. In dephell you can create setup.py from poetry without requirements.txt. I will notify you when this project is done.

**Comment by rominf** [comment]
Noooo!
I need requirements.txt because PyCharm warns if I import libraries that are not in requirements.txt.
I also don't see the point in generating the setup.py, as poetry can do it itself.

**Comment by orsinium** [comment]
Don't panic, [dephell](https://github.com/orsinium/dephell) will be able to do it too. Soon :)

**Comment by orsinium** [comment]
[DepHell](https://github.com/dephell/dephell) is ready, use [dephell deps convert](https://dephell.readthedocs.io/en/latest/cmd-deps-convert.html) to generate requirements.txt:

```bash
dephell deps convert --from=pyproject.toml --to=requirements.txt
```
