### ISSUE TITLE
Add git tags for releases

### ISSUE THREAD

**Issue by felixonmars** [orsinium/poetry-setup#9]
It would be nice to keep PyPI releases and git tags in sync :)

**Comment by orsinium** [comment]
Thank you for the issue :) Please, notice this message in poetry-setup's readme:

> **DEPRECATION WARNING:** poetry-setup is deprecated, use [DepHell](https://github.com/dephell/dephell) instead. It can do all these things ([dephell deps convert](https://dephell.readthedocs.io/en/latest/cmd-deps-convert.html) command) and much more.

Command [dephell project bump](https://dephell.readthedocs.io/en/latest/cmd-project-bump.html) is exactly what you want. The feature you're looking for works by default in current DepHell release, but will require `--tag` flag in future dephell release (see [#106](https://github.com/dephell/dephell/issues/106) for details).

Feel free to open an issue in DepHell if you need some features :)

**Comment by eli-schwartz** [comment]
The issue is not whether dephell project bump can do that, but whether it has in fact been done. This repository does not contain the correct tags.

**Comment by orsinium** [comment]
Oh, got it. There will no more releases. Consider `0.3.6` as `master`, don't use older releases. For DepHell all releases tagged.
